include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
    deprecated_member_use_from_same_package: ignore
  exclude:
    - backup_nav_running_20260816/**

linter:
  rules:
    prefer_const_constructors: false
    avoid_print: false
